# -*- coding: utf-8 -*-
# Copyright (c) 2026, WALLIX
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the Markdown reference of the collection's plugins in docs/.

Reads the plugin documentation with ``ansible-doc --json`` and writes one page per plugin in
docs/modules/ and docs/lookup/, plus the index docs/README.md.

    python docs/generate_docs.py          # write the pages
    python docs/generate_docs.py --check  # fail if the pages are out of date
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

import argparse
import ast
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
NAMESPACE = "wallix"
NAME = "bastion"
FQCN_PREFIX = "%s.%s." % (NAMESPACE, NAME)

# Plugin type -> directory of its pages in docs/.
PLUGIN_DIRS = {"module": "modules", "lookup": "lookup"}

# Index sections. Every module except the _info ones must be listed; each _info module is shown
# next to its module, and _info modules without a module go in "Read-only".
CATEGORIES = [
    ("Devices", [
        "device", "device_service", "device_localdomain", "device_localdomain_account",
        "device_localdomain_account_credential",
    ]),
    ("Applications", [
        "application", "application_localdomain", "application_localdomain_account",
        "application_localdomain_account_credential",
    ]),
    ("Global domains", ["domain", "domain_account", "domain_account_credential"]),
    ("Users and access", ["user", "usergroup", "targetgroup", "authorization", "profile", "timeframe"]),
    ("Policies", ["connection_policy", "checkout_policy", "passwordchangepolicy"]),
    ("Authentication", [
        "authdomain_ad", "authdomain_azuread", "authdomain_ldap", "authdomain_saml", "authdomain_mapping",
        "externalauth_kerberos", "externalauth_ldap", "externalauth_radius", "externalauth_saml",
        "externalauth_tacacs",
    ]),
    ("API keys", ["apikey", "apikey_v2"]),
    ("Appliance", [
        "cluster", "certificate_authority", "notification", "connection_message", "config_smtp",
        "config_wsm", "config_x509", "encryption",
    ]),
    ("Secrets", ["secret"]),
]

GENERATED = "<!-- Generated by docs/generate_docs.py from the plugin documentation. Do not edit. -->"


def plugin_names(plugin_type):
    path = os.path.join(ROOT, "plugins", PLUGIN_DIRS[plugin_type])
    return sorted(f[:-3] for f in os.listdir(path) if f.endswith(".py") and not f.startswith("_"))


def load_docs(plugin_type, names):
    """Return {name: ansible-doc JSON} for the plugins of one type."""
    tmp = tempfile.mkdtemp()
    try:
        os.makedirs(os.path.join(tmp, "ansible_collections", NAMESPACE))
        os.symlink(ROOT, os.path.join(tmp, "ansible_collections", NAMESPACE, NAME))
        env = dict(os.environ, ANSIBLE_COLLECTIONS_PATH=tmp, ANSIBLE_NOCOLOR="1")
        proc = subprocess.Popen(
            ["ansible-doc", "--json", "-t", plugin_type] + [FQCN_PREFIX + n for n in names],
            env=env, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        )
        out, err = proc.communicate()
        if proc.returncode:
            raise SystemExit("ansible-doc failed:\n%s" % err.decode("utf-8", "replace"))
    finally:
        shutil.rmtree(tmp)
    data = json.loads(out)
    missing = [n for n in names if FQCN_PREFIX + n not in data]
    if missing:
        raise SystemExit("ansible-doc returned no documentation for %s" % ", ".join(missing))
    return dict((n, data[FQCN_PREFIX + n]) for n in names)


def page_link(plugin_type, name, from_type):
    """Relative link from a page of from_type to the page of a plugin."""
    target = "%s.md" % name
    if plugin_type != from_type:
        target = "../%s/%s" % (PLUGIN_DIRS[plugin_type], target)
    return target


def anchor(prefix, path):
    return "%s-%s" % (prefix, "-".join(path).replace("_", "-").lower())


class Markup(object):
    """Convert Ansible documentation markup to Markdown, for one page."""

    RE = re.compile(r"\b(C|V|O|E|M|P|RV|I|B|U|L)\(((?:[^()\\]|\\.)*)\)|\bHORIZONTALLINE\b")

    def __init__(self, plugin_type, options, returns):
        self.plugin_type = plugin_type
        self.options = options
        self.returns = returns

    def __call__(self, text, table=False):
        if isinstance(text, list):
            parts = [self(t, table) for t in text]
            return "<br>".join(parts) if table else "\n\n".join(parts)
        text = self.RE.sub(self._sub, str(text))
        if table:
            text = text.replace("|", "\\|").replace("\n", " ")
        return text

    def _sub(self, m):
        kind, arg = m.group(1), m.group(2)
        if kind is None:
            return ""
        arg = re.sub(r"\\(.)", r"\1", arg)
        if kind in ("C", "V", "E"):
            return code(arg)
        if kind == "I":
            return "*%s*" % arg
        if kind == "B":
            return "**%s**" % arg
        if kind == "U":
            return "<%s>" % arg
        if kind == "L":
            label, url = arg.rsplit(",", 1)
            return "[%s](%s)" % (label.strip(), url.strip())
        if kind == "M":
            return self._plugin(arg, "module")
        if kind == "P":
            fqcn, plugin_type = arg.split("#", 1)
            return self._plugin(fqcn, plugin_type)
        if kind in ("O", "RV"):
            return self._field(arg, kind)
        return m.group(0)

    def _plugin(self, fqcn, plugin_type):
        if fqcn.startswith(FQCN_PREFIX) and plugin_type in PLUGIN_DIRS:
            name = fqcn[len(FQCN_PREFIX):]
            return "[%s](%s)" % (code(fqcn), page_link(plugin_type, name, self.plugin_type))
        return code(fqcn)

    def _field(self, arg, kind):
        # O(name), O(name=value), O(a.b), O(fqcn#type:name): link to fields of this page only.
        name = arg.split("=", 1)[0]
        if "#" in name or ":" in name:
            return code(arg.split(":", 1)[-1])
        path = re.sub(r"\[[^\]]*\]", "", name).split(".")
        fields, prefix, key = (
            (self.options, "parameter", "suboptions") if kind == "O" else (self.returns, "return", "contains")
        )
        for i, part in enumerate(path):
            if not isinstance(fields, dict) or part not in fields:
                return code(arg)
            fields = fields[part].get(key) if i < len(path) - 1 else None
        return "[%s](#%s)" % (code(arg), anchor(prefix, path))


def code(text):
    text = str(text)
    fence = "``" if "`" in text else "`"
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return "%s%s%s%s%s" % (fence, pad, text, pad, fence)


def value(v):
    """Inline representation of a default, choice or sample."""
    if isinstance(v, str):
        return code('"%s"' % v) if v == "" or v.strip() != v else code(v)
    return code(json.dumps(v, sort_keys=True))


def type_of(field):
    t = field.get("type", "str")
    if field.get("elements"):
        t = "%s / elements=%s" % (t, field["elements"])
    return t


def option_rows(options, md, path=()):
    rows = []
    for name in sorted(options):
        opt = options[name]
        p = path + (name,)
        label = "%s**%s**" % ("&nbsp;&nbsp;&nbsp;&nbsp;" * len(path) + ("↳ " if path else ""), name)
        cell = ['<a id="%s"></a>%s' % (anchor("parameter", p), label), code(type_of(opt))]
        if opt.get("required"):
            cell[-1] += " / required"
        if opt.get("version_added") and opt.get("version_added_collection") == NAMESPACE + "." + NAME:
            cell[-1] += "<br>*added in %s*" % opt["version_added"]
        comments = md(opt.get("description", []), table=True)
        if "choices" in opt:
            choices = []
            for choice in opt["choices"]:
                c = value(choice)
                choices.append("%s (default)" % c if "default" in opt and choice == opt["default"] else c)
            comments += "<br><br>Choices: " + ", ".join(choices)
        elif opt.get("default") is not None:
            comments += "<br><br>Default: " + value(opt["default"])
        for kind, title in (("env", "Environment variable"), ("vars", "Variable"), ("ini", "INI entry")):
            entries = opt.get(kind) or []
            if entries:
                if kind == "ini":
                    names = ["`[%s] %s`" % (e["section"], e["key"]) for e in entries]
                else:
                    names = [code(e["name"]) for e in entries]
                comments += "<br><br>%s: %s" % (title, ", ".join(names))
        cell.append(comments)
        rows.append("| %s |" % " | ".join(cell))
        if opt.get("suboptions"):
            rows.extend(option_rows(opt["suboptions"], md, p))
    return rows


def return_rows(returns, md, samples, path=()):
    rows = []
    for name in sorted(returns):
        ret = returns[name]
        p = path + (name,)
        label = "%s**%s**" % ("&nbsp;&nbsp;&nbsp;&nbsp;" * len(path) + ("↳ " if path else ""), name)
        comments = md(ret.get("description", []), table=True)
        if ret.get("returned"):
            comments += "<br><br>Returned: " + md(ret["returned"], table=True)
        if "choices" in ret:
            comments += "<br><br>Choices: " + ", ".join(value(c) for c in ret["choices"])
        if "sample" in ret:
            sample = ret["sample"]
            if isinstance(sample, (dict, list)) and len(json.dumps(sample)) > 60:
                samples.append((p, sample))
                comments += "<br><br>Sample: see [below](#%s)" % anchor("sample", p)
            else:
                comments += "<br><br>Sample: " + value(sample)
        cell = ['<a id="%s"></a>%s' % (anchor("return", p), label), code(type_of(ret)), comments]
        rows.append("| %s |" % " | ".join(cell))
        if ret.get("contains"):
            rows.extend(return_rows(ret["contains"], md, samples, p))
    return rows


def dump_yaml(data):
    return yaml.safe_dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True).rstrip()


def render_plugin(plugin_type, name, data):
    doc = data["doc"]
    options = doc.get("options") or {}
    returns = data.get("return") or {}
    md = Markup(plugin_type, options, returns)
    fqcn = FQCN_PREFIX + name
    kind = "module" if plugin_type == "module" else "%s plugin" % plugin_type

    out = [GENERATED, "", "# %s" % fqcn, "", "%s — %s" % (md(doc["short_description"]), kind), ""]
    if doc.get("version_added"):
        out += ["*Added in version %s of `%s.%s`.*" % (doc["version_added"], NAMESPACE, NAME), ""]

    out += ["## Synopsis", ""]
    out += ["- %s" % md(d) for d in doc.get("description", [])]
    out += [""]

    if doc.get("requirements"):
        out += ["## Requirements", ""] + ["- %s" % md(r) for r in doc["requirements"]] + [""]

    if options:
        out += ["## Parameters", "", "| Parameter | Type | Comments |", "|---|---|---|"]
        out += option_rows(options, md)
        out += [""]

    if doc.get("attributes"):
        out += ["## Attributes", "", "| Attribute | Support | Description |", "|---|---|---|"]
        for attr in sorted(doc["attributes"]):
            a = doc["attributes"][attr]
            support = a.get("support", "")
            if a.get("details"):
                support += "<br>" + md(a["details"], table=True)
            out.append("| **%s** | %s | %s |" % (attr, support, md(a.get("description", []), table=True)))
        out += [""]

    if doc.get("notes"):
        out += ["## Notes", ""] + ["- %s" % md(n) for n in doc["notes"]] + [""]

    if doc.get("seealso"):
        out += ["## See also", ""]
        for ref in doc["seealso"]:
            if "module" in ref:
                line = md("M(%s)" % ref["module"])
            elif "plugin" in ref:
                line = md("P(%s#%s)" % (ref["plugin"], ref["plugin_type"]))
            elif "link" in ref:
                line = "[%s](%s)" % (ref["name"], ref["link"])
            else:
                line = "[%s](https://docs.ansible.com/ansible/latest/%s.html)" % (ref["description"], ref["ref"])
            if ref.get("description") and ("module" in ref or "plugin" in ref or "link" in ref):
                line += " — %s" % md(ref["description"])
            out.append("- %s" % line)
        out += [""]

    if data.get("examples"):
        out += ["## Examples", "", "```yaml", data["examples"].strip("\n"), "```", ""]

    if returns:
        samples = []
        title = "Return values" if plugin_type == "module" else "Return value"
        out += ["## %s" % title, "", "| Key | Type | Description |", "|---|---|---|"]
        out += return_rows(returns, md, samples)
        out += [""]
        for path, sample in samples:
            out += ['<a id="%s"></a>' % anchor("sample", path), "",
                    "### Sample of `%s`" % ".".join(path), "", "```yaml", dump_yaml(sample), "```", ""]

    authors = doc.get("author") or []
    if isinstance(authors, str):
        authors = [authors]
    if authors:
        out += ["## Authors", ""] + ["- %s" % a for a in authors] + [""]

    out += ["---", "", "[Back to the collection documentation](%s)" % ("../README.md"), ""]
    return "\n".join(out)


def render_index(docs):
    modules = docs["module"]
    listed = set()
    out = [
        GENERATED, "",
        "# wallix.bastion collection documentation", "",
        "Reference of the plugins of the `wallix.bastion` collection, generated from their",
        "documentation (the same as `ansible-doc wallix.bastion.<name>`).", "",
        "- [Collection overview, requirements and connection settings](../README.md)",
        "- [Adding a module](developing.md)",
        "- [Changelog](../CHANGELOG.rst)", "",
        "All modules share the [connection options](#connection-options).", "",
        "## Modules", "",
    ]
    for title, names in CATEGORIES:
        out += ["### %s" % title, "", "| Module | Read-only module | Description |", "|---|---|---|"]
        for name in names:
            if name not in modules:
                raise SystemExit("docs/generate_docs.py lists %s, which is not a module" % name)
            info = name + "_info"
            listed.update([name, info])
            info_cell = "[%s](modules/%s.md)" % (code(info), info) if info in modules else ""
            out.append("| [%s](modules/%s.md) | %s | %s |" % (
                code(name), name, info_cell, modules[name]["doc"]["short_description"]))
        out += [""]

    unlisted = sorted(n for n in modules if n not in listed)
    not_info = [n for n in unlisted if not n.endswith("_info")]
    if not_info:
        raise SystemExit("Add %s to CATEGORIES in docs/generate_docs.py" % ", ".join(not_info))
    if unlisted:
        out += ["### Read-only", "", "| Module | Description |", "|---|---|"]
        for name in unlisted:
            out.append("| [%s](modules/%s.md) | %s |" % (code(name), name, modules[name]["doc"]["short_description"]))
        out += [""]

    for plugin_type, plugins in sorted(docs.items()):
        if plugin_type == "module" or not plugins:
            continue
        out += ["## %s plugins" % plugin_type.capitalize(), "", "| Plugin | Description |", "|---|---|"]
        for name in sorted(plugins):
            out.append("| [%s](%s/%s.md) | %s |" % (
                code(FQCN_PREFIX + name), PLUGIN_DIRS[plugin_type], name,
                plugins[name]["doc"]["short_description"]))
        out += [""]

    connection = connection_fragment()
    md = Markup("module", connection["options"], {})
    out += ["## Connection options", "",
            "Every module accepts these options, from the `wallix.bastion.connection` documentation fragment.", "",
            "| Parameter | Type | Comments |", "|---|---|---|"]
    out += option_rows(connection["options"], md)
    out += [""] + ["- %s" % md(n) for n in connection.get("notes", [])] + [""]
    return "\n".join(out)


def connection_fragment():
    """The DOCUMENTATION of plugins/doc_fragments/connection.py, parsed."""
    path = os.path.join(ROOT, "plugins", "doc_fragments", "connection.py")
    with open(path) as f:
        tree = ast.parse(f.read(), path)
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and any(getattr(t, "id", None) == "DOCUMENTATION" for t in node.targets):
            return yaml.safe_load(ast.literal_eval(node.value))
    raise SystemExit("No DOCUMENTATION in %s" % path)


def generate():
    """Return {path relative to docs/: content}."""
    docs = {}
    for plugin_type in PLUGIN_DIRS:
        names = plugin_names(plugin_type)
        docs[plugin_type] = load_docs(plugin_type, names) if names else {}
    files = {"README.md": render_index(docs)}
    for plugin_type, plugins in docs.items():
        for name, data in plugins.items():
            files["%s/%s.md" % (PLUGIN_DIRS[plugin_type], name)] = render_plugin(plugin_type, name, data)
    return files


def existing():
    """Generated files currently in docs/."""
    found = set()
    for directory in PLUGIN_DIRS.values():
        path = os.path.join(DOCS, directory)
        if os.path.isdir(path):
            found.update("%s/%s" % (directory, f) for f in os.listdir(path) if f.endswith(".md"))
    if os.path.exists(os.path.join(DOCS, "README.md")):
        found.add("README.md")
    return found


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if docs/ is not up to date")
    args = parser.parse_args()

    files = generate()
    stale = sorted(existing() - set(files))
    changed = []
    for rel, content in sorted(files.items()):
        path = os.path.join(DOCS, rel)
        current = None
        if os.path.exists(path):
            with open(path) as f:
                current = f.read()
        if current != content:
            changed.append(rel)
            if not args.check:
                if not os.path.isdir(os.path.dirname(path)):
                    os.makedirs(os.path.dirname(path))
                with open(path, "w") as f:
                    f.write(content)

    if args.check:
        if changed or stale:
            for rel in changed:
                print("out of date: docs/%s" % rel)
            for rel in stale:
                print("stale: docs/%s" % rel)
            print("Run: python docs/generate_docs.py")
            return 1
        return 0

    for rel in stale:
        os.remove(os.path.join(DOCS, rel))
    print("%d pages written, %d updated, %d removed" % (len(files), len(changed), len(stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
