#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright (c) 2026, WALLIX
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r"""
module: config_wsm
short_description: Manage the Web Session Manager configuration of a WALLIX Bastion
version_added: 1.1.0
description:
  - Update the Web Session Manager (WSM) integration settings of the Bastion.
  - Equivalent of the C(wallix-bastion_config_wsm) Terraform resource.
  - Requires API version V(v3.12) or later.
  - The WSM configuration is a singleton that always exists on the Bastion and has no delete endpoint,
    so the module only offers O(state=present).
author:
  - WALLIX (@wallix)
extends_documentation_fragment:
  - wallix.bastion.connection
attributes:
  check_mode:
    description: Can run in check_mode and return changed status prediction without modifying target.
    support: full
  diff_mode:
    description: Will return details on what has changed (or possibly needs changing in check_mode), when in diff mode.
    support: full
options:
  hostname:
    description:
      - Host name of the Web Session Manager.
      - Use V("") to clear it.
    type: str
  jwe_public:
    description:
      - Public key the Bastion uses to encrypt (JWE) the tokens it sends to the Web Session Manager.
      - Use V("") to clear it.
    type: str
  state:
    description:
      - Only V(present) is supported. The WSM configuration cannot be deleted.
    type: str
    choices: [present]
    default: present
notes:
  - Options left unset keep their current value on the Bastion.
  - The JWS key pair (C(jws_public) in RV(config_wsm)) is generated by the Bastion and cannot be set.
"""

EXAMPLES = r"""
- name: Point the Bastion at its Web Session Manager
  wallix.bastion.config_wsm:
    hostname: wsm.example.com

- name: Remove the WSM host name
  wallix.bastion.config_wsm:
    hostname: ""
"""

RETURN = r"""
config_wsm:
  description:
    - The WSM configuration as returned by the Bastion API after the change. The private JWS key is not returned.
    - In check mode, the expected configuration.
    - Unset values are returned as V("").
  returned: always
  type: dict
  sample:
    hostname: wsm.example.com
    jwe_public: ""
    jws_public: "-----BEGIN PUBLIC KEY-----\nMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQB...\n-----END PUBLIC KEY-----\n"
changed_fields:
  description: Options that differed from the Bastion and were updated.
  returned: always
  type: list
  elements: str
  sample: [hostname]
"""

from ansible_collections.wallix.bastion.plugins.module_utils.resource import (
    BastionModule,
    BastionResource,
)

FIELDS = ("hostname", "jwe_public")


class SingletonResource(BastionResource):
    """One configuration object at a fixed path: GET <path> to read it, PUT <path> to change it."""

    def read(self):
        return self.normalize(self.client.get(self.path) or {})

    def update(self, current, desired):
        values = {f: current[f] for f in self.fields
                  if current.get(f) is not None and f not in self.secret_fields}
        values.update(desired)
        self.client.call("PUT", self.path, self.body(values))
        return self.read()


class WSMConfig(SingletonResource):
    def normalize(self, obj):
        obj = dict(obj)
        obj.pop("jws_private", None)
        for field in FIELDS:
            if obj.get(field) is None:
                obj[field] = ""
        return obj

    def body(self, values):
        # The API refuses "" but clears a field set to null; both fields are always sent, like the provider.
        return {f: values.get(f) or None for f in FIELDS}


def main():
    module = BastionModule(
        argument_spec=dict(
            hostname=dict(type="str"),
            jwe_public=dict(type="str"),
            state=dict(type="str", choices=["present"], default="present"),
        ),
        supports_check_mode=True,
    )
    if module.client.api_version == "v3.8":
        module.fail_json(msg="config_wsm requires API version v3.12 or later")
    resource = WSMConfig(
        module,
        path="config/wsm",
        name_field=None,
        fields=FIELDS,
        result_key="config_wsm",
    )
    resource.ensure("present")


if __name__ == "__main__":
    main()
